import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'
import State from './O5_State.jsx'
import Toggle from './O6_Toggle_or_Hide.jsx'
import MultiCond from './O7_Multiple_Condition.jsx'
import Props from './O8_Props.jsx'
import Input from './O9_Input_field.jsx'
import Component from './O10_Controlled_Component.jsx'
import CheckBox from './O11_Handle_CheckBox.jsx'
import Radio from './O12_Radio_Button.jsx'
import HandleData from './O13_Loop_and_Map.jsx'
import ReuseComp from './O14_Reuse_component.jsx'
import Clock from './O_Task_O1_Clock.jsx'
import Array from './O15_Array_Nested_loop.jsx'
import Effect from './O16_Hooks_O1_useEffect.jsx'
import Style from './O19_Style_css.jsx'
import CssModule from './O20_Css_Modules.jsx'
import StyledCom from './O21_Styled_Component.jsx'
import BootStrap from './O22_Bootstrap.jsx'
import UseRef from './O23_useRef.jsx'
import UnCtrlComponent from './O24_Uncontrolled_component.jsx'
import PassFun from './O25_Pass_Function.jsx'
import ForwordRef from './O26_ForwardRef.jsx'
import UseFormStatus from './O27_useFormStatus_hook.jsx'
import FormStatus from './O27_useFormStatus_hook.jsx'
import Transition from './O28_UseTransition_hook.jsx'
import Pure from './O29_Pure_Component_function.jsx'
import Derived from './O30_Derived_state.jsx'
import LifitingUp from './O31_Lifting_State_up.jsx'
import Updating from './O32_Updating_Object_state.jsx'
import UpdateArray from './O33_Update_Array_state.jsx'
import UseActionState from './O34_UseActionState_Hook.jsx'
import UseID from './O35_UseID_hook.jsx'
import CreateContext from './O37_Context_API.jsx'
import Customhook from './O38_Custom_Hooks.jsx'
import Router_React from './O39_React_Router.jsx'
import RouterReact from './O39_React_Router.jsx'
import {BrowserRouter} from 'react-router'
import BrowserRou from './O40_NavBar.jsx'
import PageNotFound from './O41_404_pageNotFound.jsx'
import Collage from './Collage.jsx'
import NestedRout from './O42_Nested_Routing.jsx'
import CollageDetails from './Example/O42_Collage.jsx'
import LayoutIndex from './O43_Layout_and_Index_Routes.jsx'
import Prefix from './O44_Prefix_Rout.jsx'
import DynamicRout from './O45_Dynamic_Route.jsx'
import Optioanl from './O46_Optional_Segment.jsx'
import ContactForm from './O47_Email_sending.jsx'
import NavBar from './O48_NavLink.jsx'
import NavBarLinkProcess from './O48_NavLink.jsx'
import API from './O49_API_GET_method.jsx'
createRoot(document.getElementById('root')).render(
 
 <BrowserRouter>
 <StrictMode>
    <API/>
  </StrictMode>
  </BrowserRouter>,
)
